// src/app/livros/page.tsx
import { Metadata } from 'next'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { BookOpen, Star, Download, Eye, ArrowRight, Users, Award, Calendar } from 'lucide-react'
import Link from 'next/link'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Livros | António Yosica',
  description: 'Biblioteca completa de livros de António Yosica sobre SEO, marketing digital, marca pessoal e empreendedorismo.',
  keywords: 'livros António Yosica, e-books, método LEE, SEO, marketing digital, empreendedorismo',
}

const books = [
  {
    id: 'metodo-lee',
    title: 'Método LEE',
    subtitle: 'O Guia Definitivo para Transformar Pessoas Invisíveis em Referências Visíveis',
    description: 'A metodologia completa que já transformou mais de 500 profissionais em autoridades reconhecidas em seus nichos.',
    cover: '/livro-metodo-lee-cover.png',
    price: '€29',
    rating: 4.9,
    reviews: 2847,
    readers: '10K+',
    pages: 250,
    publishDate: '2024-01-15',
    category: 'Marca Pessoal',
    status: 'Disponível',
    badges: ['Bestseller #1', 'Mais Popular'],
    freeChapters: 3,
    totalChapters: 10
  },
  {
    id: 'seo-estrategico',
    title: 'SEO Estratégico',
    subtitle: 'Domine os Resultados de Busca e Transforme Visitantes em Clientes',
    description: 'Estratégias avançadas de SEO técnico e de conteúdo para dominar o Google e gerar resultados consistentes.',
    cover: '/livro-seo-estrategico-cover.png',
    price: '€35',
    rating: 4.8,
    reviews: 1523,
    readers: '7K+',
    pages: 320,
    publishDate: '2024-02-20',
    category: 'SEO',
    status: 'Disponível',
    badges: ['Novo'],
    freeChapters: 2,
    totalChapters: 12
  },
  {
    id: 'autoridade-digital',
    title: 'Autoridade Digital',
    subtitle: 'Como Construir uma Reputação Online que Gera Oportunidades',
    description: 'O passo a passo completo para se tornar uma autoridade reconhecida no mundo digital.',
    cover: '/livro-autoridade-digital-cover.png',
    price: '€25',
    rating: 4.7,
    reviews: 892,
    readers: '5K+',
    pages: 180,
    publishDate: '2024-03-10',
    category: 'Marketing Digital',
    status: 'Disponível',
    badges: [],
    freeChapters: 3,
    totalChapters: 8
  },
  {
    id: 'empreendedor-digital',
    title: 'O Empreendedor Digital',
    subtitle: 'Da Ideia ao Negócio Escalável no Mundo Online',
    description: 'Guia completo para criar, lançar e escalar negócios digitais de sucesso.',
    cover: '/livro-empreendedor-digital-cover.png',
    price: '€32',
    rating: 0,
    reviews: 0,
    readers: '0',
    pages: 280,
    publishDate: '2024-05-15',
    category: 'Empreendedorismo',
    status: 'Pré-venda',
    badges: ['Em Breve'],
    freeChapters: 0,
    totalChapters: 15
  }
]

const categories = ['Todos', 'Marca Pessoal', 'SEO', 'Marketing Digital', 'Empreendedorismo']

export default function LivrosPage() {
  return (
    <div className="pt-20">
      {/* Hero Section */}
      <section className="py-24 bg-gradient-to-br from-brand-cream/30 via-white to-brand-orange/10">
        <div className="max-w-7xl mx-auto px-6 lg:px-8 text-center">
          <h1 className="text-4xl sm:text-5xl font-bold mb-6">
            Biblioteca <span className="bg-gradient-to-r from-brand-orange to-brand-cream bg-clip-text text-transparent">Digital</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            Conhecimento transformador em formato digital. Livros práticos sobre SEO, 
            marketing digital, marca pessoal e empreendedorismo.
          </p>
          <div className="flex items-center justify-center gap-8 text-sm text-muted-foreground">
            <div className="text-center">
              <div className="font-bold text-2xl text-brand-orange">4</div>
              <div>Livros Publicados</div>
            </div>
            <div className="text-center">
              <div className="font-bold text-2xl text-brand-orange">22K+</div>
              <div>Leitores</div>
            </div>
            <div className="text-center">
              <div className="font-bold text-2xl text-brand-orange">4.8/5</div>
              <div>Avaliação Média</div>
            </div>
          </div>
        </div>
      </section>

      {/* Categories Filter */}
      <section className="py-12 bg-white dark:bg-gray-900">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="flex flex-wrap justify-center gap-4 mb-12">
            {categories.map((category) => (
              <Button
                key={category}
                variant="outline"
                className="border-brand-orange text-brand-orange hover:bg-brand-orange hover:text-white"
              >
                {category}
              </Button>
            ))}
          </div>
        </div>
      </section>

      {/* Books Grid */}
      <section className="pb-24 bg-white dark:bg-gray-900">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
            {books.map((book) => (
              <Card key={book.id} className="hover:shadow-xl transition-all duration-300 group">
                <div className="relative">
                  <Image
                    src={book.cover || "/placeholder.svg?height=300&width=200"}
                    alt={`Capa do livro ${book.title}`}
                    width={200}
                    height={300}
                    className="w-full h-64 object-cover rounded-t-lg"
                  />
                  
                  {/* Badges */}
                  <div className="absolute top-4 left-4 space-y-2">
                    {book.badges.map((badge, index) => (
                      <Badge 
                        key={index}
                        className={`${
                          badge === 'Bestseller #1' ? 'bg-yellow-500' :
                          badge === 'Mais Popular' ? 'bg-brand-orange' :
                          badge === 'Novo' ? 'bg-green-500' :
                          badge === 'Em Breve' ? 'bg-blue-500' :
                          'bg-gray-500'
                        }`}
                      >
                        {badge}
                      </Badge>
                    ))}
                  </div>

                  {/* Status */}
                  <div className="absolute top-4 right-4">
                    <Badge variant={book.status === 'Disponível' ? 'default' : 'secondary'}>
                      {book.status}
                    </Badge>
                  </div>

                  {/* Overlay */}
                  <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity rounded-t-lg flex items-center justify-center">
                    <div className="text-center text-white">
                      <Eye className="h-8 w-8 mx-auto mb-2" />
                      <p className="text-sm">Ver Detalhes</p>
                    </div>
                  </div>
                </div>

                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between mb-2">
                    <Badge variant="secondary" className="text-xs">
                      {book.category}
                    </Badge>
                    <div className="flex items-center gap-1">
                      <Star className="h-3 w-3 fill-brand-orange text-brand-orange" />
                      <span className="text-xs text-muted-foreground">
                        {book.rating > 0 ? book.rating : 'Novo'}
                      </span>
                    </div>
                  </div>
                  <CardTitle className="text-lg line-clamp-2">{book.title}</CardTitle>
                  <p className="text-sm text-muted-foreground line-clamp-2">{book.subtitle}</p>
                </CardHeader>

                <CardContent className="pt-0">
                  <p className="text-sm text-muted-foreground mb-4 line-clamp-3">
                    {book.description}
                  </p>

                  <div className="grid grid-cols-3 gap-2 text-xs text-muted-foreground mb-4">
                    <div className="text-center">
                      <Users className="h-3 w-3 mx-auto mb-1" />
                      {book.readers}
                    </div>
                    <div className="text-center">
                      <BookOpen className="h-3 w-3 mx-auto mb-1" />
                      {book.pages}p
                    </div>
                    <div className="text-center">
                      <Calendar className="h-3 w-3 mx-auto mb-1" />
                      {new Date(book.publishDate).getFullYear()}
                    </div>
                  </div>

                  <div className="flex items-center justify-between mb-4">
                    <div className="text-2xl font-bold text-brand-orange">{book.price}</div>
                    {book.freeChapters > 0 && (
                      <div className="text-xs text-green-600">
                        {book.freeChapters} cap. grátis
                      </div>
                    )}
                  </div>

                  <div className="space-y-2">
                    {book.status === 'Disponível' ? (
                      <>
                        {book.freeChapters > 0 && (
                          <Button 
                            variant="outline" 
                            size="sm" 
                            className="w-full border-green-500 text-green-600 hover:bg-green-500 hover:text-white"
                            asChild
                          >
                            <Link href={`/livros/${book.id}/ler`}>
                              <Eye className="h-4 w-4 mr-2" />
                              Ler Grátis
                            </Link>
                          </Button>
                        )}
                        <Button 
                          size="sm" 
                          className="w-full bg-brand-orange hover:bg-brand-orange/90"
                          asChild
                        >
                          <Link href={`/livros/${book.id}`}>
                            Ver Livro
                            <ArrowRight className="h-4 w-4 ml-2" />
                          </Link>
                        </Button>
                      </>
                    ) : (
                      <Button 
                        size="sm" 
                        variant="outline"
                        className="w-full"
                        disabled
                      >
                        Em Breve
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Newsletter CTA */}
      <section className="py-24 bg-gradient-to-r from-brand-orange to-brand-cream">
        <div className="max-w-4xl mx-auto px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold text-white mb-4">
            Seja o Primeiro a Saber
          </h2>
          <p className="text-xl text-white/90 mb-8">
            Receba notificações sobre novos lançamentos e conteúdo exclusivo
          </p>
          <Button size="lg" variant="secondary" className="text-lg px-8 py-6">
            Inscrever-se na Newsletter
          </Button>
        </div>
      </section>
    </div>
  )
}

// v1/src/pages/livros/index.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Livros | António Yosica',
  description: 'Descubra os e-books de António Yosica sobre SEO, marketing digital e o Método LEE. Leia os primeiros capítulos gratuitamente.',
})

const books = [
  {
    id: 'metodo-lee',
    title: 'Método LEE: O Guia Definitivo para Dominar o SEO',
    subtitle: 'Liderança, Execução, Escalabilidade',
    description: 'Neste livro, partilho mais de 15 anos de experiência em SEO e marketing digital, apresentando o Método LEE — uma abordagem sistemática e comprovada para construir autoridade digital.',
    cover: '/images/books/metodo-lee-cover.jpg',
    price: '29,90€',
    pages: 320,
    freeChapters: 3,
    totalChapters: 12,
    rating: 4.9,
    reviews: 127,
    featured: true,
    categories: ['SEO', 'Marketing Digital', 'Estratégia'],
  },
  {
    id: 'seo-tecnico-avancado',
    title: 'SEO Técnico Avançado',
    subtitle: 'Domine os Fundamentos que 90% Ignora',
    description: 'Um mergulho profundo nas técnicas avançadas de SEO técnico. Core Web Vitals, Schema Markup, JavaScript SEO e muito mais.',
    cover: '/images/books/seo-tecnico-cover.jpg',
    price: '24,90€',
    pages: 280,
    freeChapters: 3,
    totalChapters: 10,
    rating: 4.8,
    reviews: 89,
    featured: false,
    categories: ['SEO Técnico', 'Performance', 'Desenvolvimento'],
  },
  {
    id: 'content-marketing-autoridade',
    title: 'Content Marketing para Autoridade',
    subtitle: 'Crie Conteúdo que Converte',
    description: 'Como criar conteúdo que posiciona a sua marca como líder de pensamento e gera resultados mensuráveis.',
    cover: '/images/books/content-marketing-cover.jpg',
    price: '22,90€',
    pages: 240,
    freeChapters: 3,
    totalChapters: 9,
    rating: 4.7,
    reviews: 64,
    featured: false,
    categories: ['Content Marketing', 'Copywriting', 'Branding'],
  },
]

const selectedCategory = ref('Todos')
const categories = ['Todos', 'SEO', 'Marketing Digital', 'SEO Técnico', 'Content Marketing']

const filteredBooks = computed(() => {
  if (selectedCategory.value === 'Todos') return books
  return books.filter(book => book.categories.includes(selectedCategory.value))
})
</script>

<template>
  <div>
    <!-- ═══════════════════════════════════════════════════════════════════════
         HERO SECTION
         ═══════════════════════════════════════════════════════════════════════ -->
    <section class="relative py-32 overflow-hidden">
      <div class="absolute inset-0 bg-gradient-to-br from-neutral-100 via-neutral-50 to-neutral-100 dark:from-neutral-950 dark:via-neutral-925 dark:to-neutral-950">
        <div class="absolute inset-0 bg-[linear-gradient(rgba(201,163,78,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(201,163,78,0.03)_1px,transparent_1px)] bg-[size:64px_64px]" />
      </div>

      <div class="container-default relative z-10">
        <div class="text-center max-w-3xl mx-auto">
          <span class="label text-gold-500 mb-4 block">Biblioteca Digital</span>
          <h1 class="font-display text-display-xl text-neutral-900 dark:text-neutral-100 mb-6">
            E-Books
          </h1>
          <p class="text-body-xl text-neutral-600 dark:text-neutral-400 mb-8">
            Conhecimento transformado em palavras. Leia os primeiros 3 capítulos 
            gratuitamente e descubra estratégias que transformam negócios.
          </p>
          
          <!-- Category Filter -->
          <div class="flex flex-wrap justify-center gap-3">
            <button
              v-for="category in categories"
              :key="category"
              @click="selectedCategory = category"
              class="px-4 py-2 rounded-full text-body-sm font-medium transition-all duration-300"
              :class="selectedCategory === category 
                ? 'bg-gold-500 text-neutral-950' 
                : 'bg-neutral-200 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400 hover:bg-gold-500/20'"
            >
              {{ category }}
            </button>
          </div>
        </div>
      </div>
    </section>

    <!-- ═══════════════════════════════════════════════════════════════════════
         BOOKS GRID
         ═══════════════════════════════════════════════════════════════════════ -->
    <UiSection>
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
        <NuxtLink
          v-for="book in filteredBooks"
          :key="book.id"
          :to="`/livros/${book.id}`"
          class="group"
        >
          <article class="h-full">
            <!-- Book Cover -->
            <div class="relative aspect-[3/4] rounded-2xl overflow-hidden mb-6 shadow-elegant-lg group-hover:shadow-elegant-xl transition-all duration-500">
              <!-- Placeholder Cover -->
              <div class="absolute inset-0 bg-gradient-to-br from-neutral-900 via-neutral-800 to-neutral-900">
                <div class="absolute inset-0 flex flex-col items-center justify-center p-8 text-center">
                  <div class="w-16 h-16 rounded-full bg-gold-500/20 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-500">
                    <Icon name="lucide:book-open" class="w-8 h-8 text-gold-500" />
                  </div>
                  <h3 class="font-display text-heading-lg text-neutral-100 mb-1">{{ book.title.split(':')[0] }}</h3>
                  <p class="text-body-xs text-neutral-400">António Yosica</p>
                </div>
              </div>
              
              <!-- Featured Badge -->
              <div v-if="book.featured" class="absolute top-4 left-4">
                <span class="px-3 py-1 rounded-full bg-gold-500 text-neutral-950 text-label-sm font-semibold">
                  Bestseller
                </span>
              </div>
              
              <!-- Free Preview Badge -->
              <div class="absolute bottom-4 left-4 right-4">
                <div class="px-4 py-2 rounded-xl bg-neutral-950/80 backdrop-blur-sm text-center">
                  <span class="text-body-sm text-gold-500 font-medium">
                    {{ book.freeChapters }} capítulos grátis
                  </span>
                </div>
              </div>
              
              <!-- Hover Overlay -->
              <div class="absolute inset-0 bg-gold-500/0 group-hover:bg-gold-500/10 transition-colors duration-500" />
            </div>
            
            <!-- Book Info -->
            <div>
              <div class="flex items-center gap-2 mb-2">
                <div class="flex items-center gap-1">
                  <Icon name="lucide:star" class="w-4 h-4 text-gold-500 fill-gold-500" />
                  <span class="text-body-sm text-neutral-600 dark:text-neutral-400">{{ book.rating }}</span>
                </div>
                <span class="text-neutral-400">•</span>
                <span class="text-body-sm text-neutral-500">{{ book.reviews }} reviews</span>
              </div>
              
              <h3 class="text-heading-lg text-neutral-900 dark:text-neutral-100 mb-2 group-hover:text-gold-500 transition-colors">
                {{ book.title }}
              </h3>
              
              <p class="text-body-sm text-neutral-600 dark:text-neutral-400 mb-4 line-clamp-2">
                {{ book.description }}
              </p>
              
              <div class="flex items-center justify-between">
                <span class="text-heading-lg text-gold-500 font-display">{{ book.price }}</span>
                <span class="text-body-sm text-neutral-500">{{ book.pages }} páginas</span>
              </div>
            </div>
          </article>
        </NuxtLink>
      </div>
    </UiSection>

    <!-- ═══════════════════════════════════════════════════════════════════════
         READING EXPERIENCE CTA
         ═══════════════════════════════════════════════════════════════════════ -->
    <UiSection background="alt">
      <div class="text-center max-w-3xl mx-auto">
        <Icon name="lucide:sparkles" class="w-12 h-12 text-gold-500 mx-auto mb-6" />
        <h2 class="font-display text-display-md text-neutral-900 dark:text-neutral-100 mb-6">
          Experiência de Leitura Imersiva
        </h2>
        <p class="text-body-xl text-neutral-600 dark:text-neutral-400 mb-8">
          Cada livro foi desenhado para proporcionar uma experiência de leitura única. 
          Modo noturno, tipografia otimizada, progresso sincronizado e muito mais.
        </p>
        <div class="flex flex-wrap justify-center gap-6">
          <div class="flex items-center gap-2 text-body-md text-neutral-600 dark:text-neutral-400">
            <Icon name="lucide:moon" class="w-5 h-5 text-gold-500" />
            Modo Noturno
          </div>
          <div class="flex items-center gap-2 text-body-md text-neutral-600 dark:text-neutral-400">
            <Icon name="lucide:bookmark" class="w-5 h-5 text-gold-500" />
            Marcadores
          </div>
          <div class="flex items-center gap-2 text-body-md text-neutral-600 dark:text-neutral-400">
            <Icon name="lucide:type" class="w-5 h-5 text-gold-500" />
            Tipografia Ajustável
          </div>
          <div class="flex items-center gap-2 text-body-md text-neutral-600 dark:text-neutral-400">
            <Icon name="lucide:smartphone" class="w-5 h-5 text-gold-500" />
            Leitura Offline
          </div>
        </div>
      </div>
    </UiSection>
  </div>
</template>
